### ISSUE TITLE
Robot Type

### ISSUE THREAD

**Issue by luk3Sky** [Pera-Swarm/types#3]
### Robot Type Definition

Type definition/declaration for Robot class of the simulator including swarm-server and swarm-node

#### Requirements
- [x] General Robot class
- [ ] Private/protected attributes with getters and setters
- [ ] Abstract Robot class (can be extended and declare additional functions)
- [ ] Test cases

**Comment by NuwanJ** [comment]
@luk3Sky I think you completed this. Can you update?

**Comment by luk3Sky** [comment]
@NuwanJ No, this repository should contain only type definitions, not implementations. I haven't updated this repository yet. This should be maintained according to DefinetelyTyped specs. We've postponed this repository in an earlier meeting.
