### ISSUE TITLE
Sensors Type

### ISSUE THREAD

**Issue by luk3Sky** [Pera-Swarm/types#4]
### Sensors Type Definition

Type definition/declaration for Sensor classes of the simulator including swarm-server and swarm-node

#### Requirements
- [x] Base (general) sensor class
- [x] Abstract sensor class
- [x] Factory method for creating sensor objects
- [ ] Test cases

**Comment by NuwanJ** [comment]
Are we need to implement test cases? @luk3Sky 
If not, we can close the issue now
